timestamp,message
1696144395332,"2023-10-01 07:13:11,987 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)"
1696144395333,"2023-10-01 07:13:11,988 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)"
1696144395333,"2023-10-01 07:13:12,000 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)"
1696144395333,"2023-10-01 07:13:12,001 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)"
1696144395333,"2023-10-01 07:13:12,012 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)"
1696144395333,"2023-10-01 07:13:12,012 sagemaker-training-toolkit INFO     No Neurons detected (normal if no neurons installed)"
1696144395333,"2023-10-01 07:13:12,023 sagemaker-training-toolkit INFO     Invoking user script"
1696144395333,Training Env:
1696144395334,"{
    ""additional_framework_parameters"": {},
    ""channel_input_dirs"": {},
    ""current_host"": ""algo-1"",
    ""current_instance_group"": ""homogeneousCluster"",
    ""current_instance_group_hosts"": [
        ""algo-1""
    ],
    ""current_instance_type"": ""ml.m5.large"",
    ""distribution_hosts"": [],
    ""distribution_instance_groups"": [],
    ""framework_module"": null,
    ""hosts"": [
        ""algo-1""
    ],
    ""hyperparameters"": {},
    ""input_config_dir"": ""/opt/ml/input/config"",
    ""input_data_config"": {},
    ""input_dir"": ""/opt/ml/input"",
    ""instance_groups"": [
        ""homogeneousCluster""
    ],
    ""instance_groups_dict"": {
        ""homogeneousCluster"": {
            ""instance_group_name"": ""homogeneousCluster"",
            ""instance_type"": ""ml.m5.large"",
            ""hosts"": [
                ""algo-1""
            ]
        }
    },
    ""is_hetero"": false,
    ""is_master"": true,
    ""is_modelparallel_enabled"": null,
    ""is_smddpmprun_installed"": false,
    ""job_name"": ""aaba5108-015a-4cd9-a2e3-bd1c07595e9f"",
    ""log_level"": 20,
    ""master_hostname"": ""algo-1"",
    ""model_dir"": ""/opt/ml/model"",
    ""module_dir"": ""/opt/ml/code"",
    ""module_name"": ""braket_container"",
    ""network_interface_name"": ""eth0"",
    ""num_cpus"": 2,
    ""num_gpus"": 0,
    ""num_neurons"": 0,
    ""output_data_dir"": ""/opt/ml/output/data"",
    ""output_dir"": ""/opt/ml/output"",
    ""output_intermediate_dir"": ""/opt/ml/output/intermediate"",
    ""resource_config"": {
        ""current_host"": ""algo-1"",
        ""current_instance_type"": ""ml.m5.large"",
        ""current_group_name"": ""homogeneousCluster"",
        ""hosts"": [
            ""algo-1""
        ],
        ""instance_groups"": [
            {
                ""instance_group_name"": ""homogeneousCluster"",
                ""instance_type"": ""ml.m5.large"",
                ""hosts"": [
                    ""algo-1""
                ]
            }
        ],
        ""network_interface_name"": ""eth0""
    },
    ""user_entry_point"": ""braket_container.py"""
1696144395334,}
1696144395334,Environment variables:
1696144395334,"SM_HOSTS=[""algo-1""]"
1696144395334,SM_NETWORK_INTERFACE_NAME=eth0
1696144395334,SM_HPS={}
1696144395334,SM_USER_ENTRY_POINT=braket_container.py
1696144395334,SM_FRAMEWORK_PARAMS={}
1696144395334,"SM_RESOURCE_CONFIG={""current_group_name"":""homogeneousCluster"",""current_host"":""algo-1"",""current_instance_type"":""ml.m5.large"",""hosts"":[""algo-1""],""instance_groups"":[{""hosts"":[""algo-1""],""instance_group_name"":""homogeneousCluster"",""instance_type"":""ml.m5.large""}],""network_interface_name"":""eth0""}"
1696144395334,SM_INPUT_DATA_CONFIG={}
1696144395334,SM_OUTPUT_DATA_DIR=/opt/ml/output/data
1696144395334,SM_CHANNELS=[]
1696144395334,SM_CURRENT_HOST=algo-1
1696144395334,SM_CURRENT_INSTANCE_TYPE=ml.m5.large
1696144395334,SM_CURRENT_INSTANCE_GROUP=homogeneousCluster
1696144395334,"SM_CURRENT_INSTANCE_GROUP_HOSTS=[""algo-1""]"
1696144395334,"SM_INSTANCE_GROUPS=[""homogeneousCluster""]"
1696144395334,"SM_INSTANCE_GROUPS_DICT={""homogeneousCluster"":{""hosts"":[""algo-1""],""instance_group_name"":""homogeneousCluster"",""instance_type"":""ml.m5.large""}}"
1696144395334,SM_DISTRIBUTION_INSTANCE_GROUPS=[]
1696144395335,SM_IS_HETERO=false
1696144395335,SM_MODULE_NAME=braket_container
1696144395335,SM_LOG_LEVEL=20
1696144395335,SM_FRAMEWORK_MODULE=
1696144395335,SM_INPUT_DIR=/opt/ml/input
1696144395335,SM_INPUT_CONFIG_DIR=/opt/ml/input/config
1696144395335,SM_OUTPUT_DIR=/opt/ml/output
1696144395335,SM_NUM_CPUS=2
1696144395335,SM_NUM_GPUS=0
1696144395335,SM_NUM_NEURONS=0
1696144395335,SM_MODEL_DIR=/opt/ml/model
1696144395335,SM_MODULE_DIR=/opt/ml/code
1696144395335,"SM_TRAINING_ENV={""additional_framework_parameters"":{},""channel_input_dirs"":{},""current_host"":""algo-1"",""current_instance_group"":""homogeneousCluster"",""current_instance_group_hosts"":[""algo-1""],""current_instance_type"":""ml.m5.large"",""distribution_hosts"":[],""distribution_instance_groups"":[],""framework_module"":null,""hosts"":[""algo-1""],""hyperparameters"":{},""input_config_dir"":""/opt/ml/input/config"",""input_data_config"":{},""input_dir"":""/opt/ml/input"",""instance_groups"":[""homogeneousCluster""],""instance_groups_dict"":{""homogeneousCluster"":{""hosts"":[""algo-1""],""instance_group_name"":""homogeneousCluster"",""instance_type"":""ml.m5.large""}},""is_hetero"":false,""is_master"":true,""is_modelparallel_enabled"":null,""is_smddpmprun_installed"":false,""job_name"":""aaba5108-015a-4cd9-a2e3-bd1c07595e9f"",""log_level"":20,""master_hostname"":""algo-1"",""model_dir"":""/opt/ml/model"",""module_dir"":""/opt/ml/code"",""module_name"":""braket_container"",""network_interface_name"":""eth0"",""num_cpus"":2,""num_gpus"":0,""num_neurons"":0,""output_data_dir"":""/opt/ml/output/data"",""output_dir"":""/opt/ml/output"",""output_intermediate_dir"":""/opt/ml/output/intermediate"",""resource_config"":{""current_group_name"":""homogeneousCluster"",""current_host"":""algo-1"",""current_instance_type"":""ml.m5.large"",""hosts"":[""algo-1""],""instance_groups"":[{""hosts"":[""algo-1""],""instance_group_name"":""homogeneousCluster"",""instance_type"":""ml.m5.large""}],""network_interface_name"":""eth0""},""user_entry_point"":""braket_container.py""}"
1696144395335,SM_USER_ARGS=[]
1696144395335,SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
1696144395335,PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/local/lib/python310.zip:/usr/local/lib/python3.10:/usr/local/lib/python3.10/lib-dynload:/usr/local/lib/python3.10/site-packages
1696144395335,Invoking script with the following command:
1696144395335,/usr/local/bin/python3.10 braket_container.py
1696144395335,"2023-10-01 07:13:12,025 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker Debugger as it is not installed."
1696144395335,"2023-10-01 07:13:12,025 sagemaker-training-toolkit INFO     Exceptions not imported for SageMaker TF as Tensorflow is not installed."
1696144395335,Boto3 Version:  1.28.53
1696144395335,Beginning Setup
1696144395335,Checking for Additional Requirements
1696144395335,Additional Requirements Check Finished
1696144395335,Running Code As Subprocess
1696144395335,Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/site-packages (3.6.3)
1696144395335,"Collecting matplotlib
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/b5/24/aaccf324ce862bb82277e8814d2aebbb2a2c160d04e95aa2b8c9dc3137a9/matplotlib-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading matplotlib-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)"
1696144395336,Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/site-packages (from matplotlib) (1.1.1)
1696144395336,Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/site-packages (from matplotlib) (0.11.0)
1696144395336,Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/site-packages (from matplotlib) (4.42.1)
1696144395336,Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/site-packages (from matplotlib) (1.4.5)
1696144395336,"Requirement already satisfied: numpy<2,>=1.21 in /usr/local/lib/python3.10/site-packages (from matplotlib) (1.23.5)"
1696144395336,Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/site-packages (from matplotlib) (23.1)
1696144395336,Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/site-packages (from matplotlib) (10.0.1)
1696144395336,Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/site-packages (from matplotlib) (3.1.1)
1696144395336,Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/site-packages (from matplotlib) (2.8.2)
1696144395336,Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
1696144395336,"Downloading matplotlib-3.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 77.8 MB/s eta 0:00:00"
1696144395336,"Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.6.3
    Uninstalling matplotlib-3.6.3:
      Successfully uninstalled matplotlib-3.6.3"
1696144396336,Successfully installed matplotlib-3.8.0
1696144396336,WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1696144396336,Successfully installed matplotlib
1696144397337,Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (1.23.5)
1696144397337,"Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/9b/5a/f265a1ba3641d16b5480a217a6aed08cceef09cd173b568cd5351053472a/numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)"
1696144398337,     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 1.7 MB/s eta 0:00:00
1696144398337,"Downloading numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 66.5 MB/s eta 0:00:00"
1696144398337,"Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5"
1696144399338,"    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5"
1696144401340,ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
1696144401340,"pennylane 0.31.0 requires numpy<1.24, but you have numpy 1.26.0 which is incompatible."
1696144401340,"scipy 1.9.3 requires numpy<1.26.0,>=1.18.5, but you have numpy 1.26.0 which is incompatible."
1696144401340,Successfully installed numpy-1.26.0
1696144401341,WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1696144401341,Successfully installed numpy
1696144402341,Requirement already satisfied: scipy in /usr/local/lib/python3.10/site-packages (1.9.3)
1696144402341,"Collecting scipy
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/18/44/7e8d208eb59a8224fcc474415104f13be9b378be8da63f76dfde12ec2b44/scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.8 MB/s eta 0:00:00"
1696144402341,"Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /usr/local/lib/python3.10/site-packages (from scipy) (1.26.0)"
1696144402341,Downloading scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
1696144403341,   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 34.6 MB/s eta 0:00:00
1696144403341,"Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.9.3"
1696144404342,"    Uninstalling scipy-1.9.3:
      Successfully uninstalled scipy-1.9.3"
1696144408343,ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
1696144408343,"pennylane 0.31.0 requires numpy<1.24, but you have numpy 1.26.0 which is incompatible."
1696144408343,"pennylane 0.31.0 requires scipy<=1.10, but you have scipy 1.11.3 which is incompatible."
1696144408343,Successfully installed scipy-1.11.3
1696144408343,WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1696144408343,Successfully installed scipy
1696144408343,"Collecting pyqubo
  Downloading pyqubo-1.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (245 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.3/245.3 kB 4.7 MB/s eta 0:00:00"
1696144408343,Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/site-packages (from pyqubo) (1.26.0)
1696144409344,"Collecting dimod<0.13,>=0.9.14 (from pyqubo)
  Obtaining dependency information for dimod<0.13,>=0.9.14 from https://files.pythonhosted.org/packages/ac/d1/a497cba0a0ca25b02ed373b344a63a16738995cde84768d5c65fb6b3b096/dimod-0.12.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading dimod-0.12.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)"
1696144409344,"Collecting dwave-neal>=0.5.7 (from pyqubo)
  Downloading dwave_neal-0.6.0-py3-none-any.whl (8.7 kB)"
1696144409344,"Collecting Deprecated>=1.2.12 (from pyqubo)
  Obtaining dependency information for Deprecated>=1.2.12 from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd59ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl.metadata
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)"
1696144409344,Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.10/site-packages (from pyqubo) (1.16.0)
1696144409344,"Collecting wrapt<2,>=1.10 (from Deprecated>=1.2.12->pyqubo)
  Downloading wrapt-1.15.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 18.8 MB/s eta 0:00:00"
1696144409344,"Collecting dwave-samplers<2.0.0,>=1.0.0 (from dwave-neal>=0.5.7->pyqubo)
  Obtaining dependency information for dwave-samplers<2.0.0,>=1.0.0 from https://files.pythonhosted.org/packages/2e/61/18adc0a728fe8303b6d269a97f1dcb5ad85e51167e23a9d95cc169ac4341/dwave_samplers-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading dwave_samplers-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.9 kB)"
1696144409344,"Requirement already satisfied: networkx>=2.4.0 in /usr/local/lib/python3.10/site-packages (from dwave-samplers<2.0.0,>=1.0.0->dwave-neal>=0.5.7->pyqubo) (3.1)"
1696144409344,Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
1696144409344,Downloading dimod-0.12.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
1696144410344,   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 62.8 MB/s eta 0:00:00
1696144410344,"Downloading dwave_samplers-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 90.2 MB/s eta 0:00:00"
1696144410345,"Installing collected packages: wrapt, dimod, dwave-samplers, Deprecated, dwave-neal, pyqubo"
1696144411345,Successfully installed Deprecated-1.2.14 dimod-0.12.12 dwave-neal-0.6.0 dwave-samplers-1.1.0 pyqubo-1.4.0 wrapt-1.15.0
1696144411345,WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1696144411345,Successfully installed pyqubo
1696144412345,Requirement already satisfied: networkx in /usr/local/lib/python3.10/site-packages (3.1)
1696144412345,WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1696144413346,Successfully installed networkx
1696144415346,code starts here
1696144415346,QAOA starts here
1696144415346,optimization starts here
1696144513369,optimization ends here
1696144513369,QAOA ends here
1696144513369,interation number:  1
1696144513369,Approximation starts here
1696144513369,QAOA starts here
1696144513369,optimization starts here
1696144621403,optimization ends here
1696144621403,QAOA ends here
1696144621403,Approximation ends here
1696144621403,Approximation starts here
1696144621403,QAOA starts here
1696144621403,optimization starts here
1696144725427,optimization ends here
1696144725427,QAOA ends here
1696144725427,Approximation ends here
1696144725427,[1.0]
1696144725427,Code Run Finished
1696144725427,"2023-10-01 07:18:45,239 sagemaker-training-toolkit INFO     Reporting training SUCCESS"